spring:

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/tierrating
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:please-change-this-secret-key-in-production}
    expiration-time: ${JWT_EXPIRATION_TIME:3600000}

services:
  anilist:
    client:
      key: ${ANILIST_CLIENT_KEY:}
      secret: ${ANILIST_CLIENT_SECRET:}
    url: ${ANILIST_REDIRECT_URL:}
  trakt:
    client:
      key: ${TRAKT_CLIENT_KEY:}
      secret: ${TRAKT_CLIENT_SECRET:}
    url: ${TRAKT_REDIRECT_URL:}
tmdb:
  api:
    key: ${TMDB_API_KEY:}