GET http://localhost:8080/anilist/ratzzfatzz/manga

###

GET http://localhost:8080/anilist/RatzzFatzzarst

###

GRAPHQL https://graphql.anilist.co

query userExists($name: String) {
    User(name: $name) {
        id
        name
    }
}

{
  "name": "ratzzfatzz"
}

###

GRAPHQL https://graphql.anilist.co

query ExampleQuery($userName: String, $type: MediaType, $status: MediaListStatus, $page: Int, $perPage: Int) {
    Page(page: $page, perPage: $perPage) {
        pageInfo {
            currentPage
            hasNextPage
            perPage
        }
        mediaList(userName: $userName, type: $type, status: $status) {
            score(format: POINT_10)
            media {
                id
                title {
                    romaji
                    english
                    native
                }
                coverImage {
                    large
                    extraLarge
                }
            }
        }
    }
}


{
  "userName": "ratzzfatzz",
  "status": "COMPLETED",
  "type": "ANIME",
  "page": 1,
  "perPage": 500
}
